### ISSUE TITLE
TransformParamsLayer class

### ISSUE THREAD

**Issue by auroua** [MarekKowalski/DeepAlignmentNetwork#14]
Hi @MarekKowalski 
I'm reading your code. I can't understand the code in class `TransformParamsLayer`.
Can you tell me which algorithm used in this class. Thanks!

**Comment by MarekKowalski** [comment]
Hi,

The parameters of the transform are estimated using an algorithm described in Appendix D of the very old paper I am linking below:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.141.3089&rep=rep1&type=pdf

I hope that helps!

Marek

**Comment by auroua** [comment]
Thanks!
It's very kind of you.
