### ISSUE TITLE
About the training set preparation

### ISSUE THREAD

**Issue by mariolew** [MarekKowalski/DeepAlignmentNetwork#16]
In TrainingSetPreparation.py, I found that
`trainSet.PrepareData(imageDirs, None, meanShape, 100, 100000, True)`,
However, there are only about 3400 images in the 300W dataset, why did you set the nImgs=100000?

**Comment by MarekKowalski** [comment]
Hi,

It's just a random large number, it was supposed to mean "all the images" ;)

Marek

**Comment by mariolew** [comment]
OK, I see.
