### ISSUE TITLE
How can input the picture in CameraDemo.py?

### ISSUE THREAD

**Issue by fujieysedu** [MarekKowalski/DeepAlignmentNetwork#21]
Hi,
I want to change the input to the picture path, but it always reminds me that " 'numpy.ndarray' has no attribute of 'read' ", which “vis = vidIn.read()[1]” in CameraDemo.py, I don't understand the meaning of "[1]" after "read". If I delete the " 
vis = vidIn.read()[1] 
 if len(vis.shape) > 2:
        img = np.mean(vis, axis=2).astype(np.uint8)
 else:                        " 
it reminds me that “ RuntimeError: affine matrix has wrong number of rows ”.
Thanks.

**Comment by fujieysedu** [comment]
@MarekKowalski

**Comment by MarekKowalski** [comment]
Hi,

Sorry for taking a while to answer. The read method returns a bool and the image itself, hence the [1].
If you want to use an image just do "vis=your_numpy_image".

Marek

**Comment by MarekKowalski** [comment]
A piece of code that allows running the application on a single images was been added in a recent pull request.
