### ISSUE TITLE
question about camera.py

### ISSUE THREAD

**Issue by tearsland123** [MarekKowalski/DeepAlignmentNetwork#40]
Dear Marek:
  I try to utilize different pre-trained model to test performance on camera. However, I found only when useTrackingModel = True and load DAN-Menpo-tracking.npz model could work, if I set the useTrackingModel = False and load DAN.npz or the model that I trained via myself, It would generate the following err:
  File "/xxx/xxxx/DeepAlignmentNetwork-mast_back/DeepAlignmentNetwork /LandmarkImageLayer.py", line 15, in __init__
    self.offsets = np.array(list(itertools.product(range(-self.half_size, self.half_size + 1), range(-self.half_size, self.half_size + 1))))
TypeError: 'float' object cannot be interpreted as an integer
  Do you have any ideas about this err?
  Thanks

**Comment by MarekKowalski** [comment]
Have you tried adding self.half_size = int(self.half_size) before that line? I think that should fix it, I think it might be due to you having a newer version of numpy than I did back when this was written.

**Comment by tearsland123** [comment]
Thanks for your help. it was solved
