### ISSUE TITLE
Question about bestFit function

### ISSUE THREAD

**Issue by tearsland123** [MarekKowalski/DeepAlignmentNetwork#43]
Dear Marek:
  Sorry to bother you, I could not understand the process in bestFit function. I read the paper and found it aims to align the input landmark to canonical shape. However, I could not know the math form utilized behind that. If it is possible, could you give a favor to let me know that?
  Thanks for your help.

**Comment by MarekKowalski** [comment]
Hi,

This question was answered a couple of times before in some other issues, for example here:
https://github.com/MarekKowalski/DeepAlignmentNetwork/issues/38

Best regards,

Marek

**Comment by tearsland123** [comment]
Really thanks for your help. I will check the ASM paper. I am sorry for that I have not check the previous issues for similar question.

Best Regards
Li
