### ISSUE TITLE
how self.offsets + intLandmark possible?

### ISSUE THREAD

**Issue by dedoogong** [MarekKowalski/DeepAlignmentNetwork#9]
I wonder how locations = self.offsets + intLandmark  in LandmarkImageLayer.py is possible as I think self.offset = np.array(list(itertools.product(range(-self.half_size, self.half_size + 1), range(-self.half_size, self.half_size + 1)))), so it has size of (289,2), but intLandmark's size must be either (136,1) or (1,136). 

I don't know how to debug theano to see the intermediate TensorValues, so I'm trying to convert it with only numpy. and I got the size mismatch error. 

but ,Interestingly, I have no problem in running the theano code!

I'm totally puzzled!

Please let me know any hint.

Thank you in advance!

**Comment by dedoogong** [comment]
I guess, maybe,  theano.scan would do the loop with each landmark points (x,y) 68 times. 
but I tried some test code to check how heat map around each landmark point can be made as below;

import numpy as np
import cv2
import utils

from matplotlib import pyplot as plt
import itertools

halfsize=8
img = np.zeros((1, halfsize*2+1, halfsize*2+1))
offsets = np.array(list(itertools.product(range(-halfsize, halfsize+ 1), range(-halfsize, halfsize+ 1))))
locations = offsets
offsets2=offsets-np.array([0.123,0.321]) ## dxdy is float landmark value - int landmark value... why?
vals2 = 1/(1 + np.sqrt(np.sum(offsets2 * offsets2, axis=1) + 1e-6))
img[0, locations[:, 1], locations[:, 0]]=vals2
heatmap=img[0]
plt.imshow(heatmap)
plt.show()

but I got totally different shape(not circular )

can  you let me know how dxdy really looks like( it's range between 0 and 1 right?)
and why dxdy is float landmark value - int landmark value? 

I guess dxdy should be the distance that increases from the each landmark point. 
so, actually I dont understand why offsets=offsets-dxdy is needed;;;

**Comment by dedoogong** [comment]
I found all answers to the question above with below code
        halfsize = 8
        offsets = np.array(list(itertools.product(range(-halfsize, halfsize + 1), range(-halfsize, halfsize + 1))))
        dxdy=landmarks - int_landmarks
        for i in range(int_landmarks.shape[0]):
            locations = offsets + int_landmarks[i]
            offsetsSubPix = offsets-dxdy[i]
            vals = 1 / (1 + np.sqrt(np.sum(offsetsSubPix * offsetsSubPix , axis=1) + 1e-6))
            blank_image[locations[:, 1], locations[:, 0], 0] += vals
        max_value=np.max(blank_image[:,:,0])
        blank_image/=max_value

        plt.imshow(blank_image[:,:,0])

but, I have one big question in calculation of vals = 1 / (1 + np.sqrt(np.sum(offsetsSubPix * offsetsSubPix , axis=1) + 1e-6)). 

as each landmark located quite close when considering the patch size, 
1. if just assigning or overwriting the vals on each patch area
    (like blank_image[locations[:, 1], locations[:, 0], 0] = vals), it must result in a wrong heat map. 
![Alt text](https://raw.githubusercontent.com/dedoogong/asrada/77a82fb8d3df64c7b5ad2905d353356db02218ba/figure_6.png)
2. if just accumulating the vals over each patch area
    (like blank_image[locations[:, 1], locations[:, 0], 0] += vals), it would look similar with the true heat map, but lips or nose area has quite lots of landmarks, so all points look strong red(high value). 
![Alt text](https://raw.githubusercontent.com/dedoogong/asrada/77a82fb8d3df64c7b5ad2905d353356db02218ba/figure_3.png)

** true heat map is as below;
![Alt text](https://raw.githubusercontent.com/dedoogong/asrada/77a82fb8d3df64c7b5ad2905d353356db02218ba/figure_4.png)

>> how to avoid intervention of each patch with preserving each landmark's heat map value??

**Comment by MarekKowalski** [comment]
Hi,

Sorry for not answering for a couple of days now. I am quite busy recently, I will read it all and answer soon.

Marek

**Comment by MarekKowalski** [comment]
Hi,

I finally have some time to look at your question, sorry for the delay. Looking at the second comment I can tell that you have already solved your original question. As for the second question:

You should create a separate array that will hold images for each separate landmark and do img = np.max(imgs,  axis=0), I will post a modified version of your code below that does just that.

```
halfsize = 8
offsets = np.array(list(itertools.product(range(-halfsize, halfsize + 1), range(-halfsize, halfsize + 1))))
dxdy=landmarks - int_landmarks
images = np.zeros((int_landmarks.shape[0], 112, 112))

for i in range(int_landmarks.shape[0]):
    locations = offsets + int_landmarks[i]
    offsetsSubPix = offsets-dxdy[i]
    vals = 1 / (1 + np.sqrt(np.sum(offsetsSubPix * offsetsSubPix , axis=1) + 1e-6))
    images[i, locations[:, 1], locations[:, 0]] += vals

image = np.max(images, axis=0)
plt.imshow(image )
plt.show()
```

In this way only the maximum weight is held for each pixel.

Let me know if that solves the problem for you.

Marek

**Comment by dedoogong** [comment]
ahh max! i got your point ;) thank you!
